[versions]

reactor-core       = "3.6.11"
reactor-extra      = "3.5.2"
example-router-lib = "2.4.0-SNAPSHOT"
example-core-lib   = "2.4.0-SNAPSHOT"
example-logging    = "2.4.0-SNAPSHOT"
core               = "2.18.3"
spring-data        = "3.5.0"
validation         = "3.3.4"
springdoc          = "2.7.0"
lombok             = "1.18.34"
kafka              = "3.3.3"
awssdk             = "2.28.29"
junit              = "5.10.0"
mockito            = "5.11.0"
assertj            = "3.24.2"
postgres           = "42.7.7"
oracle-ojdbc       = "19.3.0.0"
oracle-jdbc        = "21.7.0.0"
jakarta-xml-bind   = "4.0.2"
jaxb-runtime       = "4.0.5"
jaxb-api           = "2.3.1"
mapstruct          = "1.5.5.Final"
logstash-logback   = "7.4"
commons-fileupload = "1.6.0"
google-gson        = "2.11.0"
logback            = "1.5.19"
resilience4j-sb3   = "2.3.0"
resilience4j       = "2.2.0"
caffeine           = "3.1.8"
hikari             = "5.1.0"
mockwebserver      = "4.12.0"
blockhound         = "1.0.15.RELEASE"
slf4j              = "2.0.9"
archunit           = "1.4.1"

[libraries]

# [CLIENT]
example-router  = { module = "com.example.lib:router", version.ref = "example-router-lib" }
example-core    = { module = "com.example.lib:core", version.ref = "example-core-lib" }
example-logging = { module = "com.example.lib:logging-spring-boot-starter", version.ref = "example-logging" }

# [Main]
spring-context         = { module = "org.springframework:spring-context" }
spring-context-support = { module = "org.springframework:spring-context-support" }
boot-starter           = { module = "org.springframework.boot:spring-boot-starter" }
boot-validation        = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "validation" }
blockhound-junit       = { module = "io.projectreactor.tools:blockhound-junit-platform", version.ref = "blockhound" }
slf4j-api              = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# [Spring Web]
boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }

# [Spring WebFlux]
boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }

# [Spring Security]
boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }

# [Observability]
boot-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }

# [Caffeine Cache]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

# [Gson]
google-gson = { module = "com.google.code.gson:gson", version.ref = "google-gson" }

# [Spring Data]
spring-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-data      = { module = "org.springframework.data:spring-data-commons", version.ref = "spring-data" }

# [JPA / R2DBC]
boot-starter-data-jpa   = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
boot-starter-data-r2dbc = { module = "org.springframework.boot:spring-boot-starter-data-r2dbc" }
r2dbc-h2                = { module = "io.r2dbc:r2dbc-h2" }
r2dbc-pool              = { module = "io.r2dbc:r2dbc-pool" }

hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }

# [Jackson]
jackson-databind    = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "core" }
jackson-core        = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "core" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "core" }

# [Springdoc OpenAPI]
boot-springdoc-webflux = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }
boot-springdoc-web     = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
projectlombok          = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

# [Jackson]
jackson-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }

# [JAXB Jakarta runtime] (Java 21)
jakarta-xml-bind = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jakarta-xml-bind" }
jaxb-runtime     = { module =  "org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxb-runtime" }
jaxb-api         = { module =  "javax.xml.bind:jaxb-api", version.ref = "jaxb-api" }
spring-ws-core   = { module =  "org.springframework.ws:spring-ws-core" }
spring-oxm       = { module =  "org.springframework:spring-oxm" }

# [Aspects]
boot-aop = { module = "org.springframework.boot:spring-boot-starter-aop" }

# [H2 Database]
h2 = { module = "com.h2database:h2" }

# [Redis Web]
boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
boot-starter-cache      = { module = "org.springframework.boot:spring-boot-starter-cache" }

# [Redis Reactive]
boot-starter-data-redis-reactive = { module = "org.springframework.boot:spring-boot-starter-data-redis-reactive" }
lettuce-core                     = { module = "io.lettuce:lettuce-core" }

# [R2DBC Postgres]
postgresql-r2dbc = { module = "org.postgresql:r2dbc-postgresql", version.ref = "postgres" }
postgresql       = { module = "org.postgresql:postgresql", version.ref = "postgres" }

# [Oracle JDBC]
oracle-ojdbc = { module = "com.oracle.ojdbc:orai18n", version.ref = "oracle-ojdbc" }
oracle-jdbc  = { module = "com.oracle.database.jdbc:ojdbc8", version.ref = "oracle-jdbc" }

# [Mapstruct]
mapstruct           = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

# [Kafka]
spring-kafka  = { module = "org.springframework.kafka:spring-kafka", version.ref = "kafka"}
kafka-clients = { module = "org.apache.kafka:kafka-clients" }

# [LogBack]
logstash-logback-encoder = { group = "net.logstash.logback", name = "logstash-logback-encoder", version.ref = "logstash-logback" }
logback-core             = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic          = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# [Commons FileUpload]
commons-fileupload = { module = "commons-fileupload:commons-fileupload", version.ref = "commons-fileupload" }

# [AWS SDK]
awssdk-cognito           = { module = "software.amazon.awssdk:cognitoidentityprovider", version.ref = "awssdk" }
awssdk-core              = { module = "software.amazon.awssdk:core", version.ref = "awssdk"  }
awssdk-regions           = { module = "software.amazon.awssdk:regions", version.ref = "awssdk"  }
awssdk-sts               = { module = "software.amazon.awssdk:sts", version.ref = "awssdk"  }
awssdk-ssm               = { module = "software.amazon.awssdk:ssm", version.ref = "awssdk"  }
awssdk-secrets-manager   = { module = "software.amazon.awssdk:secretsmanager", version.ref = "awssdk"  }
awssdk-auth              = { module = "software.amazon.awssdk:auth", version.ref = "awssdk"  }
awssdk-java-dynamodb     = { module = "com.amazonaws:aws-java-sdk-dynamodb", version.ref = "awssdk" }
awssdk-dynamodb          = { module = "software.amazon.awssdk:dynamodb", version.ref = "awssdk" }
awssdk-dynamodb-enhanced = { module = "software.amazon.awssdk:dynamodb-enhanced", version.ref = "awssdk" }
awssdk-lambda            = { module = "software.amazon.awssdk:lambda", version.ref = "awssdk"  }
awssdk-sso               = { module = "software.amazon.awssdk:sso", version.ref = "awssdk"  }
awssdk-ssooidc           = { module = "software.amazon.awssdk:ssooidc", version.ref = "awssdk"  }
awssdk-netty             = { module = "software.amazon.awssdk:netty-nio-client", version.ref = "awssdk"  }
awssdk-eventbridge       = { module = "software.amazon.awssdk:eventbridge", version.ref = "awssdk" }

# [Resilience4j]
resilience4j-circuitbreaker = { module = "io.github.resilience4j:resilience4j-circuitbreaker", version.ref = "resilience4j" }
resilience4j-reactor        = { module = "io.github.resilience4j:resilience4j-reactor", version.ref = "resilience4j" }
resilience4j-spring-boot3   = { module = "io.github.resilience4j:resilience4j-spring-boot3", version.ref = "resilience4j-sb3" }

# [OpenFeign]
spring-cloud-openfeign = { module = "org.springframework.cloud:spring-cloud-starter-openfeign" }

# [Test]
boot-test         = { module = "org.springframework.boot:spring-boot-starter-test" }
platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
reactor-core      = { module = "io.projectreactor:reactor-core", version.ref = "reactor-core" }
reactor-test      = { module = "io.projectreactor:reactor-test" }
reactor-extra     = { module = "io.projectreactor.addons:reactor-extra", version.ref = "reactor-extra" }
reactor-netty     = { module = "io.projectreactor.netty:reactor-netty" }
mockwebserver     = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
archunit          = { module = "com.tngtech.archunit:archunit", version.ref = "archunit" }

# [Test Containers]
test-containers                = { module = "org.springframework.boot:spring-boot-testcontainers" }
test-containers-junit-jupiter  = { module = "org.testcontainers:junit-jupiter" }
test-containers-elasticsearch  = { module = "org.testcontainers:elasticsearch" }

# [Test Junit]
junit-bom                   = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api           = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine        = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-suite-api    = { module = "org.junit.platform:junit-platform-suite-api" }
junit-platform-suite-engine = { module = "org.junit.platform:junit-platform-suite-engine" }

# [Test Mockito / AssertJ]
mockito-core          = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core          = { module = "org.assertj:assertj-core", version.ref = "assertj" }

boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }